name: test

on:
  pull_request:
  push:

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.2.0
        with:
          go-version: '1.17'
      - run: make test
